### ISSUE TITLE
No Response or Updating

### ISSUE THREAD

**Issue by gramster1** [kikolobo/homebridge-lutron-homeworks#16]
Hi, I have noticed as of a few hours ago all of my lights show "no response" or "updating". No actions were taken before the issue became prevalent. The accessories can still be controlled inside of the homebridge webpage with no issue. I have cloned and rebuilt the docker container running in DSM and the issue persists, the only curious thing I noticed was the line of "outputType": "AUTO_DETECT", is missing in every light configuration, and quotes around 23 in the apiPort line were missing. Are the aforementioned changes needed for the plugin to work properly? What might be causing this issue? I am running the plugin in a child bridge and have had no issues up to this point. 

Environment:
DS2415+ DSM 7.1.1-42962 Update 1
Node.js 18.12.1
Homebridge UI version 4.50.2
Homebridge version 1.5.1

**Comment by kikolobo** [comment]
Hello!

let me investigate further. For sure the parsing issues should not be there. Let me take a closer look.


This happened to me a while back but when I upgraded my hubs this resumed to worked back again properly. When this happened I used to have a bridge box from Lutron and the issue was present there too. 

Anyway, let me take a look and will get back to you ASAP in a few days.

**Comment by gramster1** [comment]
Okay thanks so much for your prompt response. Should I fix the parsing issues or will this result in the accessory cache being erased requiring I reorganize the lights? Looking forward to your response ASAP so I can get my lights working again lol

**Comment by kikolobo** [comment]
I don’t think you will have a problem if you fix the parsing issue. However I can’t guarantee it for now since I am not home and can’t see my setup 😊 but will be there Sunday.If I was to make an educated guess you should be able to change anything. Just make a sensible backup of any setting file you change. The cache should be smart enough to prevent duplicates. Saludos!FLGOn Nov 26, 2022, at 1:07 AM, Graham Werle ***@***.***> wrote:﻿
Okay thanks so much for your prompt response. Should I fix the parsing issues or will this result in the accessory cache being erased requiring I reorganize the lights? Looking forward to your response ASAP so I can get my lights working again lol

**Comment by kikolobo** [comment]
@gramster1  I checked the parsing HTML/Javascript script and in my computer all parses properly.The quotes are where they should, so I can say that the issues you are reporting are most likely due to the browser/os you are using. I will see if there's anything I should take care of in terms of specifying the format (UTF8) I should specify somewhere to force that encoding.

SO. YES you should add "" to the apiPort field. 

However.. I don't think this is the issue you are having. Have you change anything in your network? Say added a router, change ip address classes or something?  Since the quotes are in the port number it might have some effect in the network config. So lets try that.

 I would fix the parsing anyway, you could remove the "outputType" field entirely since HomeKit does nothing that I can think of with that info. That was added later on a pull request. I will investigate if this serves a reason, In my setup I don't use that field. 

I would also try resetting the bridges in my system, like Apple TVs/HomePods, etc.  It seems more likely that there's an issue there.

Please keep me posted if this fixes your issue so that I can keep investigating.

**Comment by gramster1** [comment]
Thank you for the detailed response, after some more testing - restarting homebridge, rebuilding the container etc... The lights randomly started to work again, I have removed the outputType fields with no issues. I will keep you posted if the issue re-appears. Thanks for your promptness when issues arise!!
